"""
Compiler for translating validated PrimitivePlans into executable CadQuery Python scripts.
"""

from typing import Any

from runtime.schema import LIBRARY, PrimitiveItem, PrimitivePlan


def _add_rotation_code(item: PrimitiveItem) -> str:
    """Chains rotate calls for non-zero rotation angles [rx, ry, rz]."""
    code = ""
    # Rotate around X-axis
    if item.orientation[0] != 0.0:
        code += f".rotate((0, 0, 0), (1, 0, 0), {item.orientation[0]})"
    # Rotate around Y-axis
    if item.orientation[1] != 0.0:
        code += f".rotate((0, 0, 0), (0, 1, 0), {item.orientation[1]})"
    # Rotate around Z-axis
    if item.orientation[2] != 0.0:
        code += f".rotate((0, 0, 0), (0, 0, 1), {item.orientation[2]})"
    return code


def _add_translation_code(item: PrimitiveItem) -> str:
    """Generates translate call for non-zero position coords [x, y, z]."""
    x, y, z = item.position
    if x != 0.0 or y != 0.0 or z != 0.0:
        return f".translate(({x}, {y}, {z}))"
    return ""


def _build_primitive_code(item: PrimitiveItem) -> str:
    """Builds the base primitive initialization with rotation and translation applied."""
    template = LIBRARY[item.primitive]["template"]
    formatted = template.format(**item.parameters)
    formatted += _add_rotation_code(item)
    formatted += _add_translation_code(item)
    return formatted


def _generate_step_lines(idx: int, item: PrimitiveItem) -> list[str]:
    """Generates the Python script lines for a single primitive step execution."""
    expr = _build_primitive_code(item)
    step_lines = [
        f"# Step {idx}: {item.id} ({item.primitive})",
        f"shape_{idx} = {expr}",
    ]
    if idx == 0:
        step_lines.append("result = shape_0")
    elif item.operation == "union":
        step_lines.append(f"result = result.union(shape_{idx})")
    elif item.operation == "cut":
        step_lines.append(f"result = result.cut(shape_{idx})")

    step_lines.append("")
    return step_lines


def _parse_plan_input(plan_input: Any) -> PrimitivePlan:
    """Converts varying input configurations securely to a PrimitivePlan object."""
    if isinstance(plan_input, PrimitivePlan):
        return plan_input
    if isinstance(plan_input, dict) and "plan" in plan_input:
        return PrimitivePlan.model_validate(plan_input)
    if isinstance(plan_input, list):
        return PrimitivePlan.model_validate({"plan": plan_input})
    raise ValueError("Invalid input format for primitive plan compilation")


def compile_plan_to_cadquery(plan_input: Any) -> str:
    """Compiles a primitive plan into an executable CadQuery Python script."""
    plan_obj = _parse_plan_input(plan_input)
    lines = [
        "import cadquery as cq",
        "",
        "# Generated by GAH-v2 Plan Compiler",
        "",
    ]
    for idx, item in enumerate(plan_obj.plan):
        lines.extend(_generate_step_lines(idx, item))
    return "\n".join(lines)
