"""Run a ForgeCAD (.forge.js) script: validate, export STL, optionally compare.

Wraps the `forgecad` CLI (npm install -g forgecad). Three sequential steps:
  1. forgecad run <file>                          — JS + geometry validation
  2. forgecad export stl <file> --output <path>  — emit STL for MeshLib pipeline
  3. forgecad compare 3d <ref_stl> <file> --json — 0-100 similarity (optional)

The geometry loop calls this after compile_forge; a failed run or low compare
score routes back as `forge_compile` → FailureCategory.translation_drift.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

_FORGECAD_CMD = "forgecad"
_COMPARE_PASS_THRESHOLD = 90


def _run_cmd(cmd: list[str], *, timeout: int = 60) -> tuple[int, str, str]:
    """Run a subprocess returning (returncode, stdout, stderr)."""
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)  # noqa: S603
        return r.returncode, r.stdout, r.stderr
    except subprocess.TimeoutExpired:
        return -1, "", f"command timed out after {timeout}s: {' '.join(cmd)}"
    except FileNotFoundError:
        return -1, "", "forgecad not found — install with: npm install -g forgecad"


def run_forgecad(
    forge_js_path: str,
    run_id: str,
    *,
    reference_stl: str | None = None,
    compare_threshold: int = _COMPARE_PASS_THRESHOLD,
) -> dict[str, Any]:
    """Validate a .forge.js script, export STL, and optionally compare 3D vs reference.

    Args:
        forge_js_path: Path to the .forge.js script generated by compile_forge.
        run_id: Artifact run id; STL lands in outputs/{run_id}/solid_forge.stl.
        reference_stl: Optional canonical CadQuery STL for `forgecad compare 3d`.
            Comparison is skipped when None or file missing.
        compare_threshold: Minimum compare score (0-100) for success (default 90).

    Returns:
        {
          "success": bool,
          "stl_path": str | None,
          "validate_output": str,
          "compare_score": float | None,  # None when comparison was skipped
          "compare_passed": bool | None,
          "error": str | None,
        }
    """
    from tools.artifacts import run_dir

    stl_path = run_dir(run_id) / "solid_forge.stl"

    # ── 1. Validate script ────────────────────────────────────────────────────
    rc, stdout, stderr = _run_cmd([_FORGECAD_CMD, "run", forge_js_path])
    validate_output = (stdout + stderr).strip()
    if rc != 0:
        return {
            "success": False,
            "stl_path": None,
            "validate_output": validate_output,
            "compare_score": None,
            "compare_passed": None,
            "error": f"forgecad run failed (exit {rc}): {(stderr or stdout).strip()}",
        }

    # ── 2. Export STL ─────────────────────────────────────────────────────────
    rc, stdout, stderr = _run_cmd(
        [_FORGECAD_CMD, "export", "stl", forge_js_path, "--output", str(stl_path)],
        timeout=120,
    )
    if rc != 0 or not stl_path.exists():
        return {
            "success": False,
            "stl_path": None,
            "validate_output": validate_output,
            "compare_score": None,
            "compare_passed": None,
            "error": f"forgecad export stl failed (exit {rc}): {(stderr or stdout).strip()}",
        }

    # ── 3. Compare 3D (optional) ──────────────────────────────────────────────
    compare_score: float | None = None
    compare_passed: bool | None = None

    if reference_stl and Path(reference_stl).exists():
        rc, stdout, stderr = _run_cmd(
            [
                _FORGECAD_CMD, "compare", "3d",
                reference_stl, forge_js_path,
                "--json", "--samples", "2000",
            ],
            timeout=180,
        )
        if rc == 0 and stdout.strip():
            try:
                data: dict[str, Any] = json.loads(stdout)
                # CLI may emit "score", "overall", or "similarity" key
                raw = data.get("score", data.get("overall", data.get("similarity")))
                if raw is not None:
                    compare_score = float(raw)
                    compare_passed = compare_score >= compare_threshold
                    if not compare_passed:
                        return {
                            "success": False,
                            "stl_path": str(stl_path),
                            "validate_output": validate_output,
                            "compare_score": compare_score,
                            "compare_passed": False,
                            "error": (
                                f"forgecad compare 3d score {compare_score:.1f} "
                                f"< threshold {compare_threshold} (translation_drift)"
                            ),
                        }
            except (json.JSONDecodeError, ValueError):
                compare_score = None
                compare_passed = None

    return {
        "success": True,
        "stl_path": str(stl_path),
        "validate_output": validate_output,
        "compare_score": compare_score,
        "compare_passed": compare_passed,
        "error": None,
    }
